Repository wecode-bootcamp-korea/21-1st-catchcode-frontend, pull requests merged in 2021-06, with the labels that each got.

#4 README.md
  README.md
Labels: Status: Accepted

#3 [21기 정유정] code review 수정, Login / Sign 유효성 검사 기능 완료
  .gitattributes
  public/images/view.png
  src/Components/CommonInput/CommonInput.js
  src/Components/CommonInput/CommonInput.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Sign/Sign.js
  src/Pages/Sign/Sign.scss
  src/Routes.js
  src/config.js
  src/index.js
  src/utils.js
  yarn.lock
Labels: Status: 수정 요청

#6 [21기 정유정] Add: 백엔드와 연결하여 캐치구매 제외한 나머지 기능 구현 완료
  public/data/categoriesDatas.json
  public/data/filterProductListData.json
  src/Components/Banner/Banner.js
  src/Components/FilterNav/FilterNav.js
  src/Components/FilterNav/FilterNav.scss
  src/Components/FilterProducts/FilterProducts.js
  src/Components/FilterProducts/FilterProducts.scss
  src/Components/MainProductItem/MainProuctItem.js
  src/Components/SizeSelector/SizeSelector.js
  src/Components/SizeSelector/SizeSelector.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/FilterPage/FilterPage.js
  src/Pages/FilterPage/FilterPage.scss
  src/Routes.js
  src/config.js
Labels: Status: 수정 요청, Status: 추가 기능 구현중
